---
title: "naturalness_LMM"
output: html_notebook
---

This is a R notebook to analyze the ratings of architectural images using linear mixed models.


# Data preparation

```{r load libraries, include=FALSE}
library(tidyverse)
# load the libraries for LMM
library(lme4)
library(lmerTest)
library(car)
library(emmeans)
```


```{r preprocess, include=FALSE}
# Read the two CSV files
# Set show_col_types = FALSE to keep console clean.
df   <- readr::read_csv("Data_exp1.csv",  show_col_types = FALSE)


# Set Plus as the reference level in Category
df$Category <- relevel(factor(df$Category), ref = "Combined+")
```


# Modelling
## Find the best model

```{r best model, echo=TRUE, warning=FALSE}
# find the best model
source("select_lmm.R")
best_model <- select_lmm(
  data       = df,
  dv         = "Naturalness",
  fixed_main = "Category",
  group_subj = "Participant",
  group_item = "ImageNumber",
  verbose    = TRUE
)

```

## Check the output

```{r model output}
# check the result of best model
summary(best_model)
Anova(best_model, type = 'III')
# Save the model object to a file
saveRDS(best_model, file = "nature_best_model.rds")
```

## Posthoc comparisons
```{r posthoc}
# Estimated marginal means for Category
emm_cat <- emmeans(best_model, ~ Category)

# Residual SD from the model (for standardized effect size d)
resid_sd <- sigma(best_model)

# Pairwise comparisons (Tukey)
pairwise_emm <- pairs(emm_cat, adjust = "tukey")

# Add 95% CI to pairwise results
pairwise_results <- summary(pairwise_emm, infer = TRUE) %>%
  as.data.frame() %>%
    rename(
    Comparison = contrast,
    Difference = estimate,
    Std_Error  = SE,
    DF         = df,
    z_value    = z.ratio,
    P_value    = p.value,
    CI_low     = asymp.LCL,
    CI_high    = asymp.UCL
  ) %>%
  mutate(effect_size = Difference / resid_sd) %>%
  mutate(across(where(is.numeric), ~ round(.x, 3)))

pairwise_results

```


```{r echo=FALSE}
emm_df <- as.data.frame(emm_cat)
order = c("Combined+", "Ceiling-", "Biophilic-", "Lighting-", "Combined-")
ggplot(emm_df,
       aes(x = factor(Category, levels = order),
           y = emmean,
           fill = Category)) +
  geom_col(width = 0.7) +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL),
                position = position_dodge(width = 0.8),
                width = 0.2) +
  labs(
    title = "Model-Predicted Rating by Category",
    x = "Category",
    y = "Predicted Rating"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "none",
    plot.title = element_text(face = "bold")
  )
```
